// Código corto -> nombre completo -> posición (col, row) en el mapa tipo "tile grid".
// col crece hacia el este, row crece hacia el sur — aproxima la ubicación real de cada estado.
// Este mismo "code" es lo que se guarda en Supabase y lo que usa <MapaMexico> para pintar cada casilla.
export const ESTADOS = [
  { code: "BCN", name: "Baja California", col: 1, row: 0 },
  { code: "SON", name: "Sonora", col: 2, row: 1 },
  { code: "CHH", name: "Chihuahua", col: 3, row: 1 },
  { code: "COA", name: "Coahuila", col: 4, row: 1 },
  { code: "BCS", name: "Baja California Sur", col: 1, row: 2 },
  { code: "SIN", name: "Sinaloa", col: 2, row: 2 },
  { code: "DUR", name: "Durango", col: 3, row: 2 },
  { code: "NL", name: "Nuevo León", col: 5, row: 2 },
  { code: "TAM", name: "Tamaulipas", col: 6, row: 2 },
  { code: "NAY", name: "Nayarit", col: 2, row: 3 },
  { code: "ZAC", name: "Zacatecas", col: 3, row: 3 },
  { code: "SLP", name: "San Luis Potosí", col: 4, row: 3 },
  { code: "JAL", name: "Jalisco", col: 2, row: 4 },
  { code: "AGU", name: "Aguascalientes", col: 3, row: 4 },
  { code: "GUA", name: "Guanajuato", col: 4, row: 4 },
  { code: "QUE", name: "Querétaro", col: 5, row: 4 },
  { code: "HID", name: "Hidalgo", col: 6, row: 4 },
  { code: "VER", name: "Veracruz", col: 7, row: 4 },
  { code: "COL", name: "Colima", col: 1, row: 5 },
  { code: "MIC", name: "Michoacán", col: 2, row: 5 },
  { code: "MEX", name: "Estado de México", col: 3, row: 5 },
  { code: "CDMX", name: "Ciudad de México", col: 4, row: 5 },
  { code: "TLA", name: "Tlaxcala", col: 5, row: 5 },
  { code: "PUE", name: "Puebla", col: 6, row: 5 },
  { code: "GRO", name: "Guerrero", col: 2, row: 6 },
  { code: "MOR", name: "Morelos", col: 3, row: 6 },
  { code: "OAX", name: "Oaxaca", col: 3, row: 7 },
  { code: "CHP", name: "Chiapas", col: 4, row: 8 },
  { code: "TAB", name: "Tabasco", col: 5, row: 8 },
  { code: "CAM", name: "Campeche", col: 6, row: 8 },
  { code: "YUC", name: "Yucatán", col: 7, row: 9 },
  { code: "ROO", name: "Quintana Roo", col: 8, row: 9 },
];
